title: "Michelle Liu"
author: "Michelle Liu"
description: "<b>KeroMichelle</b> <b style=\"color: #DF7D60;\">(^. _ .^)/</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
logo: favicon.ico

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # hide the box-shadow from header and footer

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:michellee0326@gmail.com"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/michelleliu6"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/keromichellee"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
